FROM quay.io/centos/centos:stream8
WORKDIR /root
RUN yum update -y && \
    yum install -y epel-release dnf-plugins-core && \
    yum config-manager --set-enabled powertools && \
    yum install -y wget R initscripts compat-openssl10 && \
    yum clean all && rm -rf /var/cache/yum

RUN wget -q https://download2.rstudio.org/server/centos7/x86_64/rstudio-server-rhel-2022.12.0-353-x86_64.rpm \
    && yum install rstudio-server-rhel-2022.12.0-353-x86_64.rpm -y \
    && rm -f rstudio-server-rhel-2022.12.0-353-x86_64.rpm
COPY run_rstudio.sh /root
RUN chmod +x run_rstudio.sh

ENTRYPOINT ./run_rstudio.sh
